# Generated by Django 4.2.6 on 2023-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskdate',
            field=models.DateField(default='2023-03-30'),
            preserve_default=False,
        ),
    ]
